XYZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('visitas/', include('visitas.urls')),
    path('reservas/', include('reservas.urls')),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio, name='inicio'),  
    path('visitas/', views.visitas, name="visitas"),
    path('reservas/', views.reservas, name="reservas"),
]

reservas/urls.py
from django.urls import path
from . import views

app_name='reservas'

urlpatterns = [
    path('', views.reservas, name='reservas'),
]

visitas/urls.py
from django.urls import path
from . import views

app_name='visitas'

urlpatterns = [
    path('', views.visitas, name='visitas'),
    path('registrar', views.registrar, name='registrar'),
    path('historial/', views.historial_visitas, name='historial_visitas'),
]

home/views.py
from django.shortcuts import render

def inicio(request):
    return render(request, '../templates/index.html')

def visitas(request):
    return render(request, 'visitas/visitas.html')

def reservas(request):
    return render(request, 'reservas/reservas.html')

home/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/style-home.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container-nav">
    <nav class="navbar navbar-expand-lg" style="background-color: goldenrod; font-family: 'logo'; font-size: 20px; box-shadow: 0px 1px 5px gray; height: auto;">
        <div class="container-fluid">
            <a class="navbar-brand" href="#" style="font-size: 25px; color: white; filter: drop-shadow(1px 1px 5px black);">XYZ</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0" >
                    <li class="nav-item">
                        <a class="nav-link" style="color: black;" href="{% url 'inicio' %}">Inicio</a>
                    </li>
    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'visitas:visitas' %}">Visitas</a>
                    </li>
    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reservas:reservas' %}">Reservar</a>
                    </li>
    
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Hola, {{ user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Perfil</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
    

    <div class="section section1">
        <div class="container" style="display: flex; align-items: center; justify-content: center; text-align: start;">
            <div class="col">
                <img src="{% static '/img/edificio.png' %}" style="width: 600px; margin-left: 100px; filter: drop-shadow(0px 1px 5px rgb(161, 122, 24));" alt="logo">
            </div>
            <div class="col">
                <h1 id="welcome-message"></h1>
                <hr>
                <p>Bienvenidos a nuestra nueva web {% if user.is_authenticated %} {{ user.username }} {% else %} usuario {% endif %}</p>
            </div>
        </div>
    </div>

    <div class="section section2">
      <h1 class="text-center">Novedades</h1>
      <p class="text-center" style="font-size: small;">Mantente actualizado</p>

      <div class="container-lol">
        <div class="card">
          <div class="box">
            <div class="content">
              <h2>➕</h2>
              <h3>Registro Visitas</h3>
              <p>Ya se encuentra disponible el registro de visitantes.</p>
              <a href="{% url 'visitas:registrar' %}">Ir a registrar</a>
            </div>
          </div>
        </div>
      
        <div class="card">
          <div class="box">
            <div class="content">
              <h2>👀</h2>
              <h3>Historial</h3>
              <p>El historial de visitas ya se encuentra disponible, revisar visitantes.</p>
              <a href="{% url 'visitas:historial_visitas' %}">Visualizar historial</a>
            </div>
          </div>
        </div>
      
        <div class="card">
          <div class="box">
            <div class="content">
              <h2>😎</h2>
              <h3>Proximamente...</h3>
              <p>Reservas de zonas recreativas del edificio.</p>
              <a href="#" disabled>Read More</a>
            </div>
          </div>
        </div>
      </div>
        
    </div>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>